name: Renovate Bot

on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Renovate
      uses: renovatebot/github-action@v40.1.2
      env:
        # RENOVATE_DRY_RUN: true
        RENOVATE_REPOSITORIES: linka-cloud/docker-machine-driver-scaleway
        RENOVATE_TOKEN: ${{ secrets.REPOSITORIES_ACCESS_TOKEN }}
