name: Renovate Bot

on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Renovate
      uses: renovatebot/github-action@40.1.2
      with:
        onboarding: false
        requireConfig: false
